/**
 * Canonical error code registry for the BE NestJS app.
 *
 * Single source of truth for every stable UPPER_SNAKE_CASE error code that
 * can be thrown via `AppException` (or its subclasses). Every code listed
 * here MUST have a matching entry in `src/common/i18n/messages.ts` (both `en`
 * and `vi`). The FE team mirrors these codes into their ARB catalog under
 * `apiError<PascalCase>` keys — see `docs/ERROR_CODES.md`.
 *
 * To add a new error code:
 *   1. Add it here (with the UPPER_SNAKE_CASE string value).
 *   2. Add an `ERROR_MESSAGES` entry in `src/common/i18n/messages.ts` with
 *      `en` and `vi` text.
 *   3. (Optional but recommended) Add a typed descriptor helper in
 *      `src/common/errors/error-descriptors.ts`.
 *   4. Document the code in `docs/ERROR_CODES.md`.
 */
export enum ErrorCode {
  // Generic
  BAD_REQUEST = 'BAD_REQUEST',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  BUSINESS_ERROR = 'BUSINESS_ERROR',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',

  // Auth & users
  EMAIL_EXISTS = 'EMAIL_EXISTS',
  INVALID_OTP = 'INVALID_OTP',
  OTP_REQUIRED = 'OTP_REQUIRED',
  OTP_COOLDOWN = 'OTP_COOLDOWN',
  OTP_ATTEMPT_LIMIT_EXCEEDED = 'OTP_ATTEMPT_LIMIT_EXCEEDED',
  TWO_FA_REQUIRED = 'TWO_FA_REQUIRED',
  ACCOUNT_BANNED = 'ACCOUNT_BANNED',
  EMAIL_VERIFICATION_DISABLED = 'EMAIL_VERIFICATION_DISABLED',
  NOT_WALLET_PLACEHOLDER = 'NOT_WALLET_PLACEHOLDER',
  USE_CONTACT_EMAIL_VERIFICATION = 'USE_CONTACT_EMAIL_VERIFICATION',
  USE_CHANGE_PASSWORD_ENDPOINT = 'USE_CHANGE_PASSWORD_ENDPOINT',
  INVALID_PAYLOAD = 'INVALID_PAYLOAD',
  INVALID_CHANGE_TYPE = 'INVALID_CHANGE_TYPE',
  AVATAR_UPLOAD_DISABLED = 'AVATAR_UPLOAD_DISABLED',
  CONTACT_EMAIL_REQUIRED = 'CONTACT_EMAIL_REQUIRED',
  INVALID_AVATAR_FORMAT = 'INVALID_AVATAR_FORMAT',
  AVATAR_REQUIRED = 'AVATAR_REQUIRED',
  INVALID_USER = 'INVALID_USER',

  // Withdrawal / onchain (user)
  WITHDRAWAL_PROCESSING = 'WITHDRAWAL_PROCESSING',
  WITHDRAWAL_DUPLICATE = 'WITHDRAWAL_DUPLICATE',
  WITHDRAWAL_NOT_FOUND = 'WITHDRAWAL_NOT_FOUND',
  WITHDRAWAL_PENDING_EXISTS = 'WITHDRAWAL_PENDING_EXISTS',
  PENDING_WITHDRAWALS = 'PENDING_WITHDRAWALS',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  WALLET_NOT_FOUND = 'WALLET_NOT_FOUND',
  INVALID_AMOUNT = 'INVALID_AMOUNT',
  INVALID_TARGET = 'INVALID_TARGET',
  TARGET_REQUIRED = 'TARGET_REQUIRED',
  INVALID_ACTION = 'INVALID_ACTION',
  INSUFFICIENT_BALANCE = 'INSUFFICIENT_BALANCE',
  ACCOUNT_FROZEN = 'ACCOUNT_FROZEN',
  CHAIN_REQUIRED = 'CHAIN_REQUIRED',
  TX_HASH_REQUIRED = 'TX_HASH_REQUIRED',
  ADMIN_INGEST_MISSING_PARAMS = 'ADMIN_INGEST_MISSING_PARAMS',
  INVALID_ADDRESS = 'INVALID_ADDRESS',
  INVALID_TRON_ADDRESS = 'INVALID_TRON_ADDRESS',
  INVALID_EVM_ADDRESS = 'INVALID_EVM_ADDRESS',
  INVALID_SIGNATURE = 'INVALID_SIGNATURE',
  WALLET_ALREADY_LINKED = 'WALLET_ALREADY_LINKED',
  WALLET_INACTIVE = 'WALLET_INACTIVE',
  LINK_NOT_FOUND = 'LINK_NOT_FOUND',
  WC_AUTH_SESSION_EXPIRED = 'WC_AUTH_SESSION_EXPIRED',
  WC_AUTH_INVALID_PAYLOAD = 'WC_AUTH_INVALID_PAYLOAD',

  // Treasury / transaction wallets
  TREASURY_WALLET_BUSY = 'TREASURY_WALLET_BUSY',
  TREASURY_WALLET_BUSY_TIMEOUT = 'TREASURY_WALLET_BUSY_TIMEOUT',
  TREASURY_WALLET_INACTIVE = 'TREASURY_WALLET_INACTIVE',
  TREASURY_WALLET_LOCKED = 'TREASURY_WALLET_LOCKED',
  TREASURY_CHAIN_UNSUPPORTED = 'TREASURY_CHAIN_UNSUPPORTED',
  TREASURY_CHAIN_NOT_EVM = 'TREASURY_CHAIN_NOT_EVM',
  TREASURY_INVALID_AMOUNT = 'TREASURY_INVALID_AMOUNT',
  TREASURY_SWEEP_USDT_ZERO = 'TREASURY_SWEEP_USDT_ZERO',
  TREASURY_USDT_CHAIN = 'TREASURY_USDT_CHAIN',
  TREASURY_CONFIRM_NO_WALLET = 'TREASURY_CONFIRM_NO_WALLET',
  TREASURY_MANUAL_SETTLE_TX_EMPTY = 'TREASURY_MANUAL_SETTLE_TX_EMPTY',
  TREASURY_OPERATION_NOT_FOUND = 'TREASURY_OPERATION_NOT_FOUND',
  TREASURY_OPERATION_STATE_INVALID = 'TREASURY_OPERATION_STATE_INVALID',
  TREASURY_OPERATION_NOT_QUEUED = 'TREASURY_OPERATION_NOT_QUEUED',
  TREASURY_OPERATION_NOT_PROCESSING = 'TREASURY_OPERATION_NOT_PROCESSING',
  TREASURY_OPERATION_NOT_CONFIRMING = 'TREASURY_OPERATION_NOT_CONFIRMING',
  TREASURY_OPERATION_NOT_COMPLETED = 'TREASURY_OPERATION_NOT_COMPLETED',
  TREASURY_OPERATION_NOT_FAILED = 'TREASURY_OPERATION_NOT_FAILED',
  TREASURY_TX_HASH_NOT_FOUND = 'TREASURY_TX_HASH_NOT_FOUND',
  TREASURY_INSUFFICIENT_FUNDS = 'TREASURY_INSUFFICIENT_FUNDS',
  TREASURY_BALANCE_RECONCILE_FAILED = 'TREASURY_BALANCE_RECONCILE_FAILED',
  TREASURY_OPERATION_TYPE_UNSUPPORTED = 'TREASURY_OPERATION_TYPE_UNSUPPORTED',
  TREASURY_RPC_UNAVAILABLE = 'TREASURY_RPC_UNAVAILABLE',
  TREASURY_RPC_TIMEOUT = 'TREASURY_RPC_TIMEOUT',
  TREASURY_GAS_ESTIMATE_FAILED = 'TREASURY_GAS_ESTIMATE_FAILED',
  TREASURY_NONCE_CONFLICT = 'TREASURY_NONCE_CONFLICT',
  TREASURY_TX_REVERTED = 'TREASURY_TX_REVERTED',
  TREASURY_TX_BROADCAST_FAILED = 'TREASURY_TX_BROADCAST_FAILED',
  TX_WALLET_EXISTS = 'TX_WALLET_EXISTS',
  TX_WALLET_NOT_FOUND = 'TX_WALLET_NOT_FOUND',
  TX_WALLET_NON_ZERO_BALANCE = 'TX_WALLET_NON_ZERO_BALANCE',
  TX_WALLET_USDT_NON_ZERO = 'TX_WALLET_USDT_NON_ZERO',
  TX_WALLET_DEFAULT_DEPOSIT_DELETE_FORBIDDEN = 'TX_WALLET_DEFAULT_DEPOSIT_DELETE_FORBIDDEN',
  TX_WALLET_OPERATION_IN_FLIGHT = 'TX_WALLET_OPERATION_IN_FLIGHT',
  DEFAULT_USER_DEPOSIT_DEACTIVATE_FORBIDDEN = 'DEFAULT_USER_DEPOSIT_DEACTIVATE_FORBIDDEN',
  TRON_USDT_DESTINATION_NOT_ACTIVATED = 'TRON_USDT_DESTINATION_NOT_ACTIVATED',
  TRON_ACCOUNT_PREFLIGHT_UNAVAILABLE = 'TRON_ACCOUNT_PREFLIGHT_UNAVAILABLE',
  TREASURY_MAIN_WALLET_NOT_FOUND = 'TREASURY_MAIN_WALLET_NOT_FOUND',
  TREASURY_MAIN_WALLET_CONFLICT = 'TREASURY_MAIN_WALLET_CONFLICT',

  // Orders / matching
  ORDER_NOT_FOUND = 'ORDER_NOT_FOUND',
  ORDER_NOT_OPEN = 'ORDER_NOT_OPEN',
  INVALID_PRICE = 'INVALID_PRICE',
  INVALID_INPUT = 'INVALID_INPUT',
  INVALID_MARKET_BUY_RESERVE = 'INVALID_MARKET_BUY_RESERVE',
  NO_LIQUIDITY = 'NO_LIQUIDITY',
  ORDER_CREATE_FAILED = 'ORDER_CREATE_FAILED',
  INVALID_STATE = 'INVALID_STATE',
  OVERFILL_ATTEMPT = 'OVERFILL_ATTEMPT',
  CANCEL_FAILED = 'CANCEL_FAILED',
  PAIR_NOT_FOUND = 'PAIR_NOT_FOUND',
  INVALID_ORDER_TYPE = 'INVALID_ORDER_TYPE',
  ORDER_BOOK_SERVICE_UNAVAILABLE = 'ORDER_BOOK_SERVICE_UNAVAILABLE',
  INVALID_DEPTH_LIMIT = 'INVALID_DEPTH_LIMIT',
  INVALID_INTERVAL = 'INVALID_INTERVAL',
  MARKET_PAIR_SYMBOL_EXISTS = 'MARKET_PAIR_SYMBOL_EXISTS',
  BASE_QUOTE_SAME = 'BASE_QUOTE_SAME',
  BASE_QUOTE_REQUIRED = 'BASE_QUOTE_REQUIRED',

  // Markets / currencies
  CURRENCY_NOT_FOUND = 'CURRENCY_NOT_FOUND',
  CURRENCY_SYMBOL_EXISTS = 'CURRENCY_SYMBOL_EXISTS',
  CURRENCY_DISABLED = 'CURRENCY_DISABLED',

  // Market maker
  MARKET_MAKER_CONFIG_NOT_FOUND = 'MARKET_MAKER_CONFIG_NOT_FOUND',
  MARKET_MAKER_CONFIG_CONFLICT = 'MARKET_MAKER_CONFIG_CONFLICT',
  MARKET_MAKER_INVALID_SPREAD = 'MARKET_MAKER_INVALID_SPREAD',
  MARKET_MAKER_INVALID_AMOUNT = 'MARKET_MAKER_INVALID_AMOUNT',
  MARKET_MAKER_NO_ACTIVE_PAIRS = 'MARKET_MAKER_NO_ACTIVE_PAIRS',
  MARKET_MAKER_PLACE_FAILED = 'MARKET_MAKER_PLACE_FAILED',

  // System config / admin
  CONFIG_KEY_NOT_FOUND = 'CONFIG_KEY_NOT_FOUND',
  CONFIG_KEY_DISALLOWED = 'CONFIG_KEY_DISALLOWED',
  CONFIG_KEY_READ_ONLY = 'CONFIG_KEY_READ_ONLY',
  CONFIG_VALUE_INVALID = 'CONFIG_VALUE_INVALID',
  ADMIN_REQUIRED = 'ADMIN_REQUIRED',
  RISK_OFFICER_REQUIRED = 'RISK_OFFICER_REQUIRED',
  FINANCE_MANAGER_REQUIRED = 'FINANCE_MANAGER_REQUIRED',

  // Deposits
  DEPOSIT_NOT_FOUND = 'DEPOSIT_NOT_FOUND',
  DEPOSIT_ALREADY_PAID = 'DEPOSIT_ALREADY_PAID',
  DEPOSIT_AMOUNT_INVALID = 'DEPOSIT_AMOUNT_INVALID',
  DEPOSIT_CHAIN_UNSUPPORTED = 'DEPOSIT_CHAIN_UNSUPPORTED',
  DEPOSIT_POLL_FAILED = 'DEPOSIT_POLL_FAILED',
  TX_FAILED = 'TX_FAILED',

  // Encryption / infra
  ENCRYPTION_FAILED = 'ENCRYPTION_FAILED',
  DECRYPTION_FAILED = 'DECRYPTION_FAILED',
  ENCRYPTED_PAYLOAD_MALFORMED = 'ENCRYPTED_PAYLOAD_MALFORMED',
  DECRYPTED_PAYLOAD_INVALID = 'DECRYPTED_PAYLOAD_INVALID',
  EXTERNAL_PROVIDER_UNAVAILABLE = 'EXTERNAL_PROVIDER_UNAVAILABLE',
  EXTERNAL_PROVIDER_RATE_LIMITED = 'EXTERNAL_PROVIDER_RATE_LIMITED',

  // Notifications / push
  NOTIFICATION_DELIVERY_FAILED = 'NOTIFICATION_DELIVERY_FAILED',
  FCM_NOT_CONFIGURED = 'FCM_NOT_CONFIGURED',

  // Tron send
  TRON_SEND_FAILED = 'TRON_SEND_FAILED',
}

export type ErrorCodeString = `${ErrorCode}`;