global:
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'severity', 'cluster', 'service']
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 12h
  receiver: 'telegram-bridge'
  routes:
    - match:
        alertname: DeadMansSwitch
      receiver: 'telegram-bridge'
      group_wait: 0s
      repeat_interval: 1h

    - match:
        severity: critical
      receiver: 'telegram-bridge'
      group_wait: 0s
      repeat_interval: 1h

    - match:
        severity: warning
      receiver: 'telegram-bridge'

receivers:
  - name: 'null'

  - name: 'telegram-bridge'
    webhook_configs:
      - url: 'http://telegram-bridge:9095/alert'
        send_resolved: true
