/**
 * MySQL ENUM values for `chain` columns — keep in sync with migrations.
 */
export const BLOCKCHAIN_CHAIN_DB_VALUES = [
  'ARBITRUM_MAINNET',
  'ARBITRUM_SEPOLIA',
  'AVALANCHE_FUJI',
  'AVALANCHE_MAINNET',
  'BASE_MAINNET',
  'BASE_SEPOLIA',
  'BSC_CHAPEL',
  'BSC_MAINNET',
  'ETH_MAINNET',
  'ETH_SEPOLIA',
  'FANTOM_MAINNET',
  'FANTOM_TESTNET',
  'GNOSIS_CHIADO',
  'GNOSIS_MAINNET',
  'LINEA_MAINNET',
  'LINEA_SEPOLIA',
  'OPTIMISM_MAINNET',
  'OPTIMISM_SEPOLIA',
  'POLYGON_AMOY',
  'POLYGON_MAINNET',
  'SOLANA_DEVNET',
  'SOLANA_MAINNET',
  'TON_MAINNET',
  'TON_TESTNET',
  'TRON_MAINNET',
  'TRON_NILE',
  'TRON_SHASTA',
] as const;

export type BlockchainChainDbValue = (typeof BLOCKCHAIN_CHAIN_DB_VALUES)[number];
