import { MigrationInterface, QueryRunner } from "typeorm";

export class BaselinePostgresSchema1800000000000 implements MigrationInterface {
    name = 'BaselinePostgresSchema1800000000000'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "currency_networks" ("network_id" character(36) NOT NULL, "currency_id" character(36) NOT NULL, "network_code" character varying(32) NOT NULL, "deposit_enabled" boolean NOT NULL DEFAULT true, "withdraw_enabled" boolean NOT NULL DEFAULT true, "min_confirmations" integer NOT NULL DEFAULT '12', "withdraw_fee" numeric(36,18) NOT NULL DEFAULT '0', "currencyCurrencyId" character(36), CONSTRAINT "PK_3023cebf977bb4317f2e5070793" PRIMARY KEY ("network_id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "uk_currency_network" ON "currency_networks" ("currency_id", "network_code") `);
        await queryRunner.query(`CREATE TABLE "market_pairs" ("pair_id" character(36) NOT NULL, "base_currency_id" character(36) NOT NULL, "quote_currency_id" character(36) NOT NULL, "symbol" character varying(32) NOT NULL, "price_scale" smallint NOT NULL DEFAULT '2', "amount_scale" smallint NOT NULL DEFAULT '6', "min_order_amount" numeric(36,18) NOT NULL DEFAULT '0.0001', "maker_fee_rate" numeric(10,8) NOT NULL DEFAULT '0.001', "taker_fee_rate" numeric(10,8) NOT NULL DEFAULT '0.001', "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_6376d86c1ea01cb29ed9e828e27" UNIQUE ("symbol"), CONSTRAINT "PK_a6ffaba71b4e8084d50aa21b8d7" PRIMARY KEY ("pair_id"))`);
        await queryRunner.query(`CREATE INDEX "idx_pair_active" ON "market_pairs" ("is_active") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "uk_pair_base_quote" ON "market_pairs" ("base_currency_id", "quote_currency_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "uk_pair_symbol" ON "market_pairs" ("symbol") `);
        await queryRunner.query(`CREATE TABLE "currencies" ("currency_id" character(36) NOT NULL, "symbol" character varying(16) NOT NULL, "name" character varying(64) NOT NULL, "precision_scale" smallint NOT NULL DEFAULT '8', "min_withdraw" numeric(36,18) NOT NULL DEFAULT '0', "is_tradable" boolean NOT NULL DEFAULT true, "is_active" boolean NOT NULL DEFAULT true, CONSTRAINT "UQ_30ed1fd0130c0874227d1817f2c" UNIQUE ("symbol"), CONSTRAINT "PK_8ea4cc194d333e79b3a8e8a9a24" PRIMARY KEY ("currency_id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "uk_currency_symbol" ON "currencies" ("symbol") `);
        await queryRunner.query(`CREATE TYPE "public"."managed_wallets_chain_enum" AS ENUM('ARBITRUM_MAINNET', 'ARBITRUM_SEPOLIA', 'AVALANCHE_FUJI', 'AVALANCHE_MAINNET', 'BASE_MAINNET', 'BASE_SEPOLIA', 'BSC_CHAPEL', 'BSC_MAINNET', 'ETH_MAINNET', 'ETH_SEPOLIA', 'FANTOM_MAINNET', 'FANTOM_TESTNET', 'GNOSIS_CHIADO', 'GNOSIS_MAINNET', 'LINEA_MAINNET', 'LINEA_SEPOLIA', 'OPTIMISM_MAINNET', 'OPTIMISM_SEPOLIA', 'POLYGON_AMOY', 'POLYGON_MAINNET', 'SOLANA_DEVNET', 'SOLANA_MAINNET', 'TON_MAINNET', 'TON_TESTNET', 'TRON_MAINNET', 'TRON_NILE', 'TRON_SHASTA')`);
        await queryRunner.query(`CREATE TABLE "managed_wallets" ("wallet_id" character(36) NOT NULL, "user_id" character(36) NOT NULL, "chain" "public"."managed_wallets_chain_enum" NOT NULL, "address" character varying(255) NOT NULL, "public_key" character varying(255) NOT NULL, "encrypted_private_key" text NOT NULL, "encrypted_seed_phrase" text, "label" character varying(100), "is_default_deposit" boolean NOT NULL DEFAULT false, "default_set_at" TIMESTAMP, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_91f744b89af1a7287b7e29362c8" PRIMARY KEY ("wallet_id"))`);
        await queryRunner.query(`CREATE INDEX "idx_managed_wallet_user_active" ON "managed_wallets" ("user_id", "is_active") `);
        await queryRunner.query(`CREATE INDEX "idx_managed_wallet_chain_default" ON "managed_wallets" ("chain", "is_default_deposit") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "uk_managed_wallet_user_chain_addr" ON "managed_wallets" ("user_id", "chain", "address") `);
        await queryRunner.query(`CREATE TYPE "public"."transaction_wallets_chain_enum" AS ENUM('ARBITRUM_MAINNET', 'ARBITRUM_SEPOLIA', 'AVALANCHE_FUJI', 'AVALANCHE_MAINNET', 'BASE_MAINNET', 'BASE_SEPOLIA', 'BSC_CHAPEL', 'BSC_MAINNET', 'ETH_MAINNET', 'ETH_SEPOLIA', 'FANTOM_MAINNET', 'FANTOM_TESTNET', 'GNOSIS_CHIADO', 'GNOSIS_MAINNET', 'LINEA_MAINNET', 'LINEA_SEPOLIA', 'OPTIMISM_MAINNET', 'OPTIMISM_SEPOLIA', 'POLYGON_AMOY', 'POLYGON_MAINNET', 'SOLANA_DEVNET', 'SOLANA_MAINNET', 'TON_MAINNET', 'TON_TESTNET', 'TRON_MAINNET', 'TRON_NILE', 'TRON_SHASTA')`);
        await queryRunner.query(`CREATE TYPE "public"."transaction_wallets_purpose_enum" AS ENUM('DEPOSIT', 'WITHDRAWAL', 'BOTH')`);
        await queryRunner.query(`CREATE TABLE "transaction_wallets" ("wallet_id" character(36) NOT NULL, "chain" "public"."transaction_wallets_chain_enum" NOT NULL, "address" character varying(255) NOT NULL, "purpose" "public"."transaction_wallets_purpose_enum" NOT NULL DEFAULT 'BOTH', "encrypted_private_key" text NOT NULL, "label" character varying(100), "is_active" boolean NOT NULL DEFAULT true, "is_default_user_deposit" boolean NOT NULL DEFAULT false, "default_set_at" TIMESTAMP(6), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_892a330c34b0c582a5263c43bb6" PRIMARY KEY ("wallet_id"))`);
        await queryRunner.query(`CREATE INDEX "idx_tx_wallet_chain_active" ON "transaction_wallets" ("chain", "is_active") `);
        await queryRunner.query(`CREATE INDEX "idx_tx_wallet_chain_purpose" ON "transaction_wallets" ("chain", "purpose") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "uk_tx_wallet_chain_address" ON "transaction_wallets" ("chain", "address") `);
        await queryRunner.query(`CREATE TYPE "public"."treasury_operations_type_enum" AS ENUM('SWEEP', 'FUND')`);
        await queryRunner.query(`CREATE TYPE "public"."treasury_operations_chain_enum" AS ENUM('ARBITRUM_MAINNET', 'ARBITRUM_SEPOLIA', 'AVALANCHE_FUJI', 'AVALANCHE_MAINNET', 'BASE_MAINNET', 'BASE_SEPOLIA', 'BSC_CHAPEL', 'BSC_MAINNET', 'ETH_MAINNET', 'ETH_SEPOLIA', 'FANTOM_MAINNET', 'FANTOM_TESTNET', 'GNOSIS_CHIADO', 'GNOSIS_MAINNET', 'LINEA_MAINNET', 'LINEA_SEPOLIA', 'OPTIMISM_MAINNET', 'OPTIMISM_SEPOLIA', 'POLYGON_AMOY', 'POLYGON_MAINNET', 'SOLANA_DEVNET', 'SOLANA_MAINNET', 'TON_MAINNET', 'TON_TESTNET', 'TRON_MAINNET', 'TRON_NILE', 'TRON_SHASTA')`);
        await queryRunner.query(`CREATE TYPE "public"."treasury_operations_status_enum" AS ENUM('PENDING', 'PROCESSING', 'TX_BROADCAST', 'COMPLETED', 'FAILED')`);
        await queryRunner.query(`CREATE TABLE "treasury_operations" ("operation_id" character(36) NOT NULL, "type" "public"."treasury_operations_type_enum" NOT NULL, "chain" "public"."treasury_operations_chain_enum" NOT NULL, "from_wallet_id" character(36), "to_wallet_id" character(36), "amount" numeric(36,18) NOT NULL DEFAULT '0', "asset" character varying(24) NOT NULL DEFAULT 'NATIVE', "tx_hash" character varying(255), "onchain_tx_id" character(36), "status" "public"."treasury_operations_status_enum" NOT NULL DEFAULT 'PENDING', "broadcast_idempotency_key" character varying(255), "actor_user_id" character(36) NOT NULL, "failure_reason" character varying(512), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "completed_at" TIMESTAMP, CONSTRAINT "PK_ad016c84a520adc20f8e010ddd8" PRIMARY KEY ("operation_id"))`);
        await queryRunner.query(`CREATE INDEX "idx_treasury_op_created" ON "treasury_operations" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "idx_treasury_op_chain_type_status" ON "treasury_operations" ("chain", "type", "status") `);
        await queryRunner.query(`CREATE TYPE "public"."users_status_enum" AS ENUM('ACTIVE', 'BANNED', 'PENDING')`);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('TRADER', 'ADMIN', 'RISK_OFFICER', 'SUPPORT_AGENT', 'MARKET_MAKER', 'FINANCE_MANAGER')`);
        await queryRunner.query(`CREATE TABLE "users" ("user_id" character(36) NOT NULL, "email" character varying(255) NOT NULL, "password_hash" character varying(255) NOT NULL, "first_name" character varying(100), "last_name" character varying(100), "two_fa_secret" bytea, "status" "public"."users_status_enum" NOT NULL DEFAULT 'ACTIVE', "role" "public"."users_role_enum" NOT NULL DEFAULT 'TRADER', "identity_verified" smallint NOT NULL DEFAULT '0', "email_verified" smallint NOT NULL DEFAULT '0', "avatar_url" character varying(512), "avatar_public_id" character varying(255), "fcm_token" character varying(512), "two_fa_enabled" smallint NOT NULL DEFAULT '0', "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_96aac72f1574b88752e9fb00089" PRIMARY KEY ("user_id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "uk_users_email" ON "users" ("email") `);
        await queryRunner.query(`CREATE TYPE "public"."withdrawals_status_enum" AS ENUM('REQUESTED', 'APPROVED', 'SENT', 'COMPLETED', 'REJECTED', 'FAILED')`);
        await queryRunner.query(`CREATE TABLE "withdrawals" ("withdraw_id" character(36) NOT NULL, "user_id" character(36) NOT NULL, "currency_id" character(36) NOT NULL, "network_id" character(36), "amount" numeric(36,18) NOT NULL, "fee" numeric(36,18) NOT NULL DEFAULT '0', "to_address" character varying(255) NOT NULL, "tx_hash" character varying(255), "status" "public"."withdrawals_status_enum" NOT NULL DEFAULT 'REQUESTED', "idempotency_key" character varying(64) NOT NULL, "requested_at" TIMESTAMP NOT NULL DEFAULT now(), "processed_at" TIMESTAMP, "userUserId" character(36), "currencyCurrencyId" character(36), "networkNetworkId" character(36), CONSTRAINT "PK_f95de34e79cfa6dc37d64ed0475" PRIMARY KEY ("withdraw_id"))`);
        await queryRunner.query(`CREATE INDEX "idx_withdraw_user" ON "withdrawals" ("user_id", "status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "uk_withdraw_idem" ON "withdrawals" ("user_id", "idempotency_key") `);
        await queryRunner.query(`CREATE TABLE "wallets" ("wallet_id" character(36) NOT NULL, "user_id" character(36) NOT NULL, "currency_id" character(36) NOT NULL, "available" numeric(36,18) NOT NULL DEFAULT '0', "frozen" numeric(36,18) NOT NULL DEFAULT '0', "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "userUserId" character(36), "currencyCurrencyId" character(36), CONSTRAINT "PK_c1cf06e248522005c350032ee3b" PRIMARY KEY ("wallet_id"))`);
        await queryRunner.query(`CREATE INDEX "idx_wallet_user" ON "wallets" ("user_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "uk_wallet_user_currency" ON "wallets" ("user_id", "currency_id") `);
        await queryRunner.query(`CREATE TYPE "public"."wallet_ledger_ref_type_enum" AS ENUM('DEPOSIT', 'WITHDRAW', 'ORDER', 'TRADE', 'ADJUST', 'TRANSFER', 'EXTERNAL_DEPOSIT', 'EXTERNAL_WITHDRAWAL', 'EXTERNAL_SYNC')`);
        await queryRunner.query(`CREATE TYPE "public"."wallet_ledger_direction_enum" AS ENUM('CREDIT', 'DEBIT')`);
        await queryRunner.query(`CREATE TABLE "wallet_ledger" ("ledger_id" character(36) NOT NULL, "user_id" character(36) NOT NULL, "currency_id" character(36) NOT NULL, "wallet_id" character(36) NOT NULL, "ref_type" "public"."wallet_ledger_ref_type_enum" NOT NULL, "ref_id" character(36) NOT NULL, "direction" "public"."wallet_ledger_direction_enum" NOT NULL, "amount" numeric(36,18) NOT NULL, "balance_after" numeric(36,18) NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "userUserId" character(36), "currencyCurrencyId" character(36), "walletWalletId" character(36), CONSTRAINT "PK_453e962ed6d1262bd231482c2b1" PRIMARY KEY ("ledger_id"))`);
        await queryRunner.query(`CREATE INDEX "idx_ledger_ref" ON "wallet_ledger" ("ref_type", "ref_id") `);
        await queryRunner.query(`CREATE INDEX "idx_ledger_user_time" ON "wallet_ledger" ("user_id", "created_at") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "uk_ledger_ref" ON "wallet_ledger" ("ref_type", "ref_id", "user_id", "currency_id", "direction") `);
        await queryRunner.query(`CREATE TYPE "public"."notifications_type_enum" AS ENUM('system', 'alert', 'promo')`);
        await queryRunner.query(`CREATE TABLE "notifications" ("notification_id" character(36) NOT NULL, "title" character varying(255) NOT NULL, "body" text NOT NULL, "type" "public"."notifications_type_enum" NOT NULL DEFAULT 'system', "created_by" character(36) NOT NULL, "data" json, "created_at" TIMESTAMP(3) NOT NULL DEFAULT now(), "creatorUserId" character(36), CONSTRAINT "PK_eaedfe19f0f765d26afafa85956" PRIMARY KEY ("notification_id"))`);
        await queryRunner.query(`CREATE INDEX "idx_notifications_created_at" ON "notifications" ("created_at") `);
        await queryRunner.query(`CREATE TABLE "user_notifications" ("id" character(36) NOT NULL, "user_id" character(36) NOT NULL, "notification_id" character(36) NOT NULL, "is_read" smallint NOT NULL DEFAULT '0', "read_at" TIMESTAMP(3), "created_at" TIMESTAMP(3) NOT NULL DEFAULT now(), "userUserId" character(36), "notificationNotificationId" character(36), CONSTRAINT "PK_569622b0fd6e6ab3661de985a2b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_un_user_unread" ON "user_notifications" ("user_id", "is_read") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "uk_user_notif" ON "user_notifications" ("user_id", "notification_id") `);
        await queryRunner.query(`CREATE TYPE "public"."treasury_main_wallets_chain_enum" AS ENUM('ARBITRUM_MAINNET', 'ARBITRUM_SEPOLIA', 'AVALANCHE_FUJI', 'AVALANCHE_MAINNET', 'BASE_MAINNET', 'BASE_SEPOLIA', 'BSC_CHAPEL', 'BSC_MAINNET', 'ETH_MAINNET', 'ETH_SEPOLIA', 'FANTOM_MAINNET', 'FANTOM_TESTNET', 'GNOSIS_CHIADO', 'GNOSIS_MAINNET', 'LINEA_MAINNET', 'LINEA_SEPOLIA', 'OPTIMISM_MAINNET', 'OPTIMISM_SEPOLIA', 'POLYGON_AMOY', 'POLYGON_MAINNET', 'SOLANA_DEVNET', 'SOLANA_MAINNET', 'TON_MAINNET', 'TON_TESTNET', 'TRON_MAINNET', 'TRON_NILE', 'TRON_SHASTA')`);
        await queryRunner.query(`CREATE TYPE "public"."treasury_main_wallets_status_enum" AS ENUM('PENDING_APPROVAL', 'ACTIVE', 'REJECTED', 'PENDING_DELETION')`);
        await queryRunner.query(`CREATE TABLE "treasury_main_wallets" ("main_wallet_id" character(36) NOT NULL, "chain" "public"."treasury_main_wallets_chain_enum" NOT NULL, "address" character varying(255) NOT NULL, "encrypted_private_key" text NOT NULL, "label" character varying(100), "is_default" boolean NOT NULL DEFAULT false, "status" "public"."treasury_main_wallets_status_enum" NOT NULL DEFAULT 'ACTIVE', "created_by" character(36), "approved_by" character(36), "approved_at" TIMESTAMP(6), "rejected_by" character(36), "rejected_at" TIMESTAMP(6), "last_rotated_at" TIMESTAMP(6), "rotation_interval_days" integer, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_9ab93f828d5947bfe9f7c188fb7" PRIMARY KEY ("main_wallet_id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "uk_tmw_chain_address" ON "treasury_main_wallets" ("chain", "address") `);
        await queryRunner.query(`CREATE INDEX "idx_tmw_status" ON "treasury_main_wallets" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_tmw_chain_default" ON "treasury_main_wallets" ("chain", "is_default") `);
        await queryRunner.query(`CREATE INDEX "idx_tmw_chain" ON "treasury_main_wallets" ("chain") `);
        await queryRunner.query(`CREATE TYPE "public"."orders_side_enum" AS ENUM('BUY', 'SELL')`);
        await queryRunner.query(`CREATE TYPE "public"."orders_type_enum" AS ENUM('LIMIT', 'MARKET')`);
        await queryRunner.query(`CREATE TYPE "public"."orders_status_enum" AS ENUM('OPEN', 'PARTIAL', 'FILLED', 'CANCELLED', 'REJECTED')`);
        await queryRunner.query(`CREATE TYPE "public"."orders_time_in_force_enum" AS ENUM('GTC', 'IOC', 'FOK')`);
        await queryRunner.query(`CREATE TABLE "orders" ("order_id" character(36) NOT NULL, "user_id" character(36) NOT NULL, "pair_id" character(36) NOT NULL, "side" "public"."orders_side_enum" NOT NULL, "type" "public"."orders_type_enum" NOT NULL, "price" numeric(36,18), "amount" numeric(36,18) NOT NULL, "filled_amount" numeric(36,18) NOT NULL DEFAULT '0', "avg_price" numeric(36,18), "status" "public"."orders_status_enum" NOT NULL DEFAULT 'OPEN', "time_in_force" "public"."orders_time_in_force_enum" NOT NULL DEFAULT 'GTC', "reserved_quote" numeric(36,18) NOT NULL DEFAULT '0', "reserved_base" numeric(36,18) NOT NULL DEFAULT '0', "client_order_id" character varying(64), "idempotency_key" character varying(64) NOT NULL, "slippage_tolerance" numeric(36,18), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_cad55b3cb25b38be94d2ce831db" PRIMARY KEY ("order_id"))`);
        await queryRunner.query(`CREATE INDEX "idx_orders_book" ON "orders" ("pair_id", "side", "status", "price", "created_at") `);
        await queryRunner.query(`CREATE INDEX "idx_orders_pair_status" ON "orders" ("pair_id", "status", "created_at") `);
        await queryRunner.query(`CREATE INDEX "idx_orders_user" ON "orders" ("user_id", "created_at") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "uk_order_idem" ON "orders" ("user_id", "idempotency_key") `);
        await queryRunner.query(`CREATE TABLE "trades" ("trade_id" character(36) NOT NULL, "pair_id" character(36) NOT NULL, "taker_order_id" character(36) NOT NULL, "maker_order_id" character(36) NOT NULL, "price" numeric(36,18) NOT NULL, "amount" numeric(36,18) NOT NULL, "taker_fee" numeric(36,18) NOT NULL DEFAULT '0', "maker_fee" numeric(36,18) NOT NULL DEFAULT '0', "fee_currency_id" character(36) NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "pairPairId" character(36), "takerOrderOrderId" character(36), "makerOrderOrderId" character(36), "feeCurrencyCurrencyId" character(36), CONSTRAINT "PK_2c21f7caf3ffad61ea326d72853" PRIMARY KEY ("trade_id"))`);
        await queryRunner.query(`CREATE INDEX "idx_trades_maker" ON "trades" ("maker_order_id") `);
        await queryRunner.query(`CREATE INDEX "idx_trades_taker" ON "trades" ("taker_order_id") `);
        await queryRunner.query(`CREATE INDEX "idx_trades_pair_time" ON "trades" ("pair_id", "created_at") `);
        await queryRunner.query(`CREATE TABLE "trade_audit_log" ("trade_id" character(36) NOT NULL, "pair_id" character(36) NOT NULL, "maker_order_id" character(36) NOT NULL, "taker_order_id" character(36) NOT NULL, "price" numeric(36,18) NOT NULL, "amount" numeric(36,18) NOT NULL, "taker_fee" numeric(36,18) NOT NULL, "maker_fee" numeric(36,18) NOT NULL, "fee_currency_id" character(36) NOT NULL, "logged_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_3f297f1a129b66156b24d6eb133" PRIMARY KEY ("trade_id"))`);
        await queryRunner.query(`CREATE INDEX "idx_audit_trade" ON "trade_audit_log" ("trade_id") `);
        await queryRunner.query(`CREATE INDEX "idx_audit_pair_time" ON "trade_audit_log" ("pair_id", "logged_at") `);
        await queryRunner.query(`CREATE TYPE "public"."system_configs_type_enum" AS ENUM('string', 'int', 'float', 'bool')`);
        await queryRunner.query(`CREATE TYPE "public"."system_configs_category_enum" AS ENUM('tech', 'finance', 'core')`);
        await queryRunner.query(`CREATE TABLE "system_configs" ("key" character varying(100) NOT NULL, "value" text NOT NULL, "type" "public"."system_configs_type_enum" NOT NULL DEFAULT 'string', "category" "public"."system_configs_category_enum" NOT NULL DEFAULT 'core', "name" character varying(255) NOT NULL, "description" text, "isReadOnly" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_5aff9a6d272a5cedf54d7aaf617" PRIMARY KEY ("key"))`);
        await queryRunner.query(`CREATE TABLE "read_onchain_deposits" ("tx_id" character(36) NOT NULL, "user_id" character(36) NOT NULL, "chain" character varying(64) NOT NULL, "type" character varying(32) NOT NULL DEFAULT 'DEPOSIT', "tx_hash" character varying(255), "from_address" character varying(255) NOT NULL DEFAULT '', "to_address" character varying(255) NOT NULL DEFAULT '', "amount" numeric(36,18) NOT NULL, "status" character varying(32) NOT NULL, "confirmations" integer NOT NULL DEFAULT '0', "settled" boolean NOT NULL DEFAULT false, "credited_currency_id" character(36), "credited_amount" numeric(36,18), "conversion_rate" numeric(36,18), "created_at" TIMESTAMP(6) NOT NULL, "confirmed_at" TIMESTAMP(6), "last_outbox_id" character(36) NOT NULL, "updated_at" TIMESTAMP(6) NOT NULL DEFAULT now(), CONSTRAINT "PK_23c32be2949bc77157361a4ce4a" PRIMARY KEY ("tx_id"))`);
        await queryRunner.query(`CREATE INDEX "idx_read_onchain_deposits_user_created" ON "read_onchain_deposits" ("user_id", "created_at") `);
        await queryRunner.query(`CREATE TABLE "read_market_trades" ("trade_id" character(36) NOT NULL, "pair_id" character(36) NOT NULL, "maker_order_id" character(36) NOT NULL, "taker_order_id" character(36) NOT NULL, "price" numeric(36,18) NOT NULL, "amount" numeric(36,18) NOT NULL, "maker_fee" numeric(36,18) NOT NULL DEFAULT '0', "taker_fee" numeric(36,18) NOT NULL DEFAULT '0', "fee_currency_id" character(36) NOT NULL, "executed_at" TIMESTAMP(6) NOT NULL, "last_outbox_id" character(36), CONSTRAINT "PK_da144780075ab4b6171452b3e1c" PRIMARY KEY ("trade_id"))`);
        await queryRunner.query(`CREATE INDEX "idx_read_market_trades_pair_executed" ON "read_market_trades" ("pair_id", "executed_at") `);
        await queryRunner.query(`CREATE TABLE "read_market_tickers" ("pair_id" character(36) NOT NULL, "symbol" character varying(32) NOT NULL, "last_price" numeric(36,18) NOT NULL, "best_bid" numeric(36,18) NOT NULL, "best_ask" numeric(36,18) NOT NULL, "volume_24h" numeric(36,18) NOT NULL DEFAULT '0', "volume_24h_usd" numeric(36,18) NOT NULL DEFAULT '0', "change_24h" numeric(36,18) NOT NULL DEFAULT '0', "change_percent_24h" numeric(36,18) NOT NULL DEFAULT '0', "high_24h" numeric(36,18) NOT NULL, "low_24h" numeric(36,18) NOT NULL, "open_24h" numeric(36,18) NOT NULL, "ticker_timestamp" TIMESTAMP(6) NOT NULL, "last_outbox_id" character(36), CONSTRAINT "PK_4d7b7ce14247fe35e52c7641655" PRIMARY KEY ("pair_id"))`);
        await queryRunner.query(`CREATE INDEX "idx_read_market_tickers_symbol" ON "read_market_tickers" ("symbol") `);
        await queryRunner.query(`CREATE TABLE "read_market_pairs" ("pair_id" character(36) NOT NULL, "symbol" character varying(32) NOT NULL, "base_currency_id" character(36) NOT NULL, "quote_currency_id" character(36) NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "updated_at" TIMESTAMP(6) NOT NULL DEFAULT now(), CONSTRAINT "PK_1cde773a492c983f1eae707aac7" PRIMARY KEY ("pair_id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_read_market_pairs_symbol" ON "read_market_pairs" ("symbol") `);
        await queryRunner.query(`CREATE TABLE "read_market_ohlcv" ("pair_id" character(36) NOT NULL, "interval_sec" integer NOT NULL, "open_time" TIMESTAMP(6) NOT NULL, "open" numeric(36,18) NOT NULL, "high" numeric(36,18) NOT NULL, "low" numeric(36,18) NOT NULL, "close" numeric(36,18) NOT NULL, "volume" numeric(36,18) NOT NULL DEFAULT '0', "quote_volume" numeric(36,18) NOT NULL DEFAULT '0', "trades_count" integer NOT NULL DEFAULT '0', "last_trade_id" character(36), "last_outbox_id" character(36), CONSTRAINT "PK_7ed833bdbb51f9af9034bfb4214" PRIMARY KEY ("pair_id", "interval_sec", "open_time"))`);
        await queryRunner.query(`CREATE INDEX "idx_read_market_ohlcv_pair_interval_time" ON "read_market_ohlcv" ("pair_id", "interval_sec", "open_time") `);
        await queryRunner.query(`CREATE TABLE "processed_integration_events" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "consumer_name" character varying(128) NOT NULL, "event_id" character(36) NOT NULL, "event_type" character varying(128) NOT NULL, "processed_at" TIMESTAMP(6) NOT NULL DEFAULT now(), CONSTRAINT "PK_471338f144bff449e3da775e7c7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_processed_integration_events_consumer_event" ON "processed_integration_events" ("consumer_name", "event_id") `);
        await queryRunner.query(`CREATE TYPE "public"."payment_method_configs_type_enum" AS ENUM('PAYOS', 'ETH', 'TRON', 'SOL', 'BSC')`);
        await queryRunner.query(`CREATE TYPE "public"."payment_method_configs_status_enum" AS ENUM('ACTIVE', 'TRANSITIONING', 'INACTIVE')`);
        await queryRunner.query(`CREATE TABLE "payment_method_configs" ("config_id" character(36) NOT NULL, "type" "public"."payment_method_configs_type_enum" NOT NULL, "network" character varying(64) NOT NULL, "display_name" character varying(128) NOT NULL, "encrypted_config" text NOT NULL, "config_version" integer NOT NULL DEFAULT '1', "status" "public"."payment_method_configs_status_enum" NOT NULL DEFAULT 'INACTIVE', "grace_period_minutes" integer NOT NULL DEFAULT '15', "transition_started_at" TIMESTAMP, "activated_at" TIMESTAMP, "sort_order" integer NOT NULL DEFAULT '0', "created_by" character(36) NOT NULL, "updated_by" character(36) NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_df35059d6b8a7bef603df6f165c" PRIMARY KEY ("config_id"))`);
        await queryRunner.query(`CREATE INDEX "idx_pmc_status" ON "payment_method_configs" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_pmc_type_network_status" ON "payment_method_configs" ("type", "network", "status") `);
        await queryRunner.query(`CREATE TABLE "market_maker_configs" ("config_id" character(36) NOT NULL, "user_id" character(36) NOT NULL, "pair_id" character(36) NOT NULL, "spread_bps" integer NOT NULL, "spread_alert_threshold_bps" integer NOT NULL DEFAULT '0', "order_amount" numeric(36,18) NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "stop_loss_pct" numeric(10,4), "max_position_base" numeric(36,18), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_3ff53295dc8e6e6125e2b7c11c8" PRIMARY KEY ("config_id"))`);
        await queryRunner.query(`CREATE INDEX "idx_mm_cfg_active" ON "market_maker_configs" ("is_active") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "uk_mm_cfg_user_pair" ON "market_maker_configs" ("user_id", "pair_id") `);
        await queryRunner.query(`CREATE TABLE "integration_outbox" ("id" character(36) NOT NULL, "aggregate_type" character varying(64) NOT NULL, "aggregate_id" character varying(64) NOT NULL, "event_type" character varying(128) NOT NULL, "payload" json NOT NULL, "occurred_at" TIMESTAMP(6) NOT NULL DEFAULT now(), "published_at" TIMESTAMP(6), "dedupe_key" character varying(191), "schema_version" integer NOT NULL DEFAULT '1', "correlation_id" character varying(191), "causation_id" character varying(191), "partition_key" character varying(191), "kafka_topic" character varying(191), "kafka_partition" integer, "kafka_offset" bigint, "kafka_published_at" TIMESTAMP(6), "publish_attempts" integer NOT NULL DEFAULT '0', "last_publish_error" text, "next_retry_at" TIMESTAMP(6), "dead_lettered_at" TIMESTAMP(6), CONSTRAINT "UQ_b39e5475bd04472998fe0be2889" UNIQUE ("dedupe_key"), CONSTRAINT "PK_0807cd3d14577a948b136b138b3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_integration_outbox_retry" ON "integration_outbox" ("published_at", "dead_lettered_at", "next_retry_at") `);
        await queryRunner.query(`CREATE INDEX "idx_integration_outbox_topic_unpublished" ON "integration_outbox" ("kafka_topic", "published_at", "occurred_at") `);
        await queryRunner.query(`CREATE INDEX "idx_integration_outbox_unpublished" ON "integration_outbox" ("published_at", "occurred_at") `);
        await queryRunner.query(`CREATE TYPE "public"."fiat_deposits_status_enum" AS ENUM('PENDING', 'PAID', 'CANCELLED')`);
        await queryRunner.query(`CREATE TABLE "fiat_deposits" ("deposit_id" character(36) NOT NULL, "user_id" character(36) NOT NULL, "amount" numeric(36,18) NOT NULL, "status" "public"."fiat_deposits_status_enum" NOT NULL DEFAULT 'PENDING', "order_code" bigint NOT NULL, "checkout_url" character varying(512), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_07837376c0445a7ddea25e32eec" UNIQUE ("order_code"), CONSTRAINT "PK_73aed03a0a53e634f66c102719c" PRIMARY KEY ("deposit_id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_fiat_deposits_order_code" ON "fiat_deposits" ("order_code") `);
        await queryRunner.query(`CREATE INDEX "idx_fiat_deposits_user" ON "fiat_deposits" ("user_id") `);
        await queryRunner.query(`CREATE TABLE "exchange_rate_audit_log" ("audit_id" character(36) NOT NULL, "changed_by" character(36) NOT NULL, "action" character varying(32) NOT NULL, "previous_rate" numeric(20,8) NOT NULL, "new_rate" numeric(20,8) NOT NULL, "previous_spread_bps" integer NOT NULL, "new_spread_bps" integer NOT NULL, "market_rate" numeric(20,8) NOT NULL, "source" character varying(32) NOT NULL, "reason" character varying(255), "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_90a8b87c2d74e2b4ad563914ca1" PRIMARY KEY ("audit_id"))`);
        await queryRunner.query(`CREATE INDEX "idx_exchange_rate_audit_created_at" ON "exchange_rate_audit_log" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "idx_exchange_rate_audit_changed_by" ON "exchange_rate_audit_log" ("changed_by") `);
        await queryRunner.query(`CREATE TYPE "public"."deposits_status_enum" AS ENUM('PENDING', 'CONFIRMED', 'CREDITED', 'FAILED')`);
        await queryRunner.query(`CREATE TABLE "deposits" ("deposit_id" character(36) NOT NULL, "user_id" character(36) NOT NULL, "currency_id" character(36) NOT NULL, "network_id" character(36), "amount" numeric(36,18) NOT NULL, "tx_hash" character varying(255) NOT NULL, "confirmations" integer NOT NULL DEFAULT '0', "status" "public"."deposits_status_enum" NOT NULL DEFAULT 'PENDING', "detected_at" TIMESTAMP NOT NULL DEFAULT now(), "credited_at" TIMESTAMP, "userUserId" character(36), "currencyCurrencyId" character(36), "networkNetworkId" character(36), CONSTRAINT "PK_ae490d8b3f198a0597b74a0465d" PRIMARY KEY ("deposit_id"))`);
        await queryRunner.query(`CREATE INDEX "idx_deposit_user" ON "deposits" ("user_id", "status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "uk_deposit_tx" ON "deposits" ("currency_id", "tx_hash") `);
        await queryRunner.query(`CREATE TABLE "deposit_watcher_cursors" ("chain" character varying(64) NOT NULL, "cursor_value" bigint NOT NULL DEFAULT '0', "cursor_kind" character varying(32) NOT NULL DEFAULT 'TIMESTAMP_MS', "updated_at" TIMESTAMP(6) NOT NULL DEFAULT now(), CONSTRAINT "PK_cfed7ed0c4c25134b602ce54b88" PRIMARY KEY ("chain"))`);
        await queryRunner.query(`CREATE TABLE "app_settings" ("k" character varying(64) NOT NULL, "v" character varying(2048) NOT NULL, "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_64b9e567543d5785e1b3ef157d5" PRIMARY KEY ("k"))`);
        await queryRunner.query(`CREATE TYPE "public"."admin_wallet_adjustments_type_enum" AS ENUM('DEPOSIT', 'WITHDRAW')`);
        await queryRunner.query(`CREATE TABLE "admin_wallet_adjustments" ("adjustment_id" character(36) NOT NULL, "actor_user_id" character(36) NOT NULL, "target_user_id" character(36) NOT NULL, "currency_id" character(36) NOT NULL, "amount" numeric(36,18) NOT NULL, "type" "public"."admin_wallet_adjustments_type_enum" NOT NULL, "note" character varying(500), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "actorUserId" character(36), "targetUserId" character(36), "currencyCurrencyId" character(36), CONSTRAINT "PK_5b886c7b87ba4c674e8d3cad935" PRIMARY KEY ("adjustment_id"))`);
        await queryRunner.query(`CREATE INDEX "idx_adj_created" ON "admin_wallet_adjustments" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "idx_adj_target" ON "admin_wallet_adjustments" ("target_user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_adj_actor" ON "admin_wallet_adjustments" ("actor_user_id") `);
        await queryRunner.query(`CREATE TYPE "public"."linked_wallets_chain_enum" AS ENUM('ARBITRUM_MAINNET', 'ARBITRUM_SEPOLIA', 'AVALANCHE_FUJI', 'AVALANCHE_MAINNET', 'BASE_MAINNET', 'BASE_SEPOLIA', 'BSC_CHAPEL', 'BSC_MAINNET', 'ETH_MAINNET', 'ETH_SEPOLIA', 'FANTOM_MAINNET', 'FANTOM_TESTNET', 'GNOSIS_CHIADO', 'GNOSIS_MAINNET', 'LINEA_MAINNET', 'LINEA_SEPOLIA', 'OPTIMISM_MAINNET', 'OPTIMISM_SEPOLIA', 'POLYGON_AMOY', 'POLYGON_MAINNET', 'SOLANA_DEVNET', 'SOLANA_MAINNET', 'TON_MAINNET', 'TON_TESTNET', 'TRON_MAINNET', 'TRON_NILE', 'TRON_SHASTA')`);
        await queryRunner.query(`CREATE TYPE "public"."linked_wallets_status_enum" AS ENUM('PENDING', 'VERIFIED', 'REVOKED')`);
        await queryRunner.query(`CREATE TABLE "linked_wallets" ("link_id" character(36) NOT NULL, "user_id" character(36) NOT NULL, "chain" "public"."linked_wallets_chain_enum" NOT NULL, "address" character varying(255) NOT NULL, "label" character varying(100), "status" "public"."linked_wallets_status_enum" NOT NULL DEFAULT 'PENDING', "linked_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_5e8118f17176dc6ff9d2f2ac54d" PRIMARY KEY ("link_id"))`);
        await queryRunner.query(`CREATE INDEX "idx_linked_wallet_user" ON "linked_wallets" ("user_id", "status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "uk_linked_wallet_user_chain_addr" ON "linked_wallets" ("user_id", "chain", "address") `);
        await queryRunner.query(`CREATE TYPE "public"."onchain_transactions_chain_enum" AS ENUM('ARBITRUM_MAINNET', 'ARBITRUM_SEPOLIA', 'AVALANCHE_FUJI', 'AVALANCHE_MAINNET', 'BASE_MAINNET', 'BASE_SEPOLIA', 'BSC_CHAPEL', 'BSC_MAINNET', 'ETH_MAINNET', 'ETH_SEPOLIA', 'FANTOM_MAINNET', 'FANTOM_TESTNET', 'GNOSIS_CHIADO', 'GNOSIS_MAINNET', 'LINEA_MAINNET', 'LINEA_SEPOLIA', 'OPTIMISM_MAINNET', 'OPTIMISM_SEPOLIA', 'POLYGON_AMOY', 'POLYGON_MAINNET', 'SOLANA_DEVNET', 'SOLANA_MAINNET', 'TON_MAINNET', 'TON_TESTNET', 'TRON_MAINNET', 'TRON_NILE', 'TRON_SHASTA')`);
        await queryRunner.query(`CREATE TYPE "public"."onchain_transactions_type_enum" AS ENUM('DEPOSIT', 'WITHDRAWAL', 'TRANSFER', 'SWEEP', 'FUND')`);
        await queryRunner.query(`CREATE TYPE "public"."onchain_transactions_status_enum" AS ENUM('UNMATCHED', 'PENDING', 'CONFIRMING', 'COMPLETED', 'FAILED')`);
        await queryRunner.query(`CREATE TABLE "onchain_transactions" ("tx_id" character(36) NOT NULL, "user_id" character(36), "linked_wallet_id" character(36), "treasury_operation_id" character(36), "chain" "public"."onchain_transactions_chain_enum" NOT NULL, "type" "public"."onchain_transactions_type_enum" NOT NULL, "tx_hash" character varying(255), "log_index" integer NOT NULL DEFAULT '0', "from_address" character varying(255) NOT NULL, "to_address" character varying(255) NOT NULL, "amount" numeric(36,18) NOT NULL, "confirmations" integer NOT NULL DEFAULT '0', "status" "public"."onchain_transactions_status_enum" NOT NULL DEFAULT 'PENDING', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "confirmed_at" TIMESTAMP, "credited_currency_id" character(36), "credited_amount" numeric(36,18), "conversion_rate" numeric(36,18), CONSTRAINT "PK_de57856646a26e952e6f0937cc1" PRIMARY KEY ("tx_id"))`);
        await queryRunner.query(`CREATE INDEX "idx_onchain_tx_treasury_operation" ON "onchain_transactions" ("treasury_operation_id") `);
        await queryRunner.query(`CREATE INDEX "idx_onchain_tx_created" ON "onchain_transactions" ("user_id", "created_at") `);
        await queryRunner.query(`CREATE INDEX "idx_onchain_tx_user" ON "onchain_transactions" ("user_id", "type", "status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "uk_onchain_tx_chain_hash_log" ON "onchain_transactions" ("chain", "tx_hash", "log_index") `);
        await queryRunner.query(`CREATE TYPE "public"."deposit_match_requests_status_enum" AS ENUM('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED')`);
        await queryRunner.query(`CREATE TABLE "deposit_match_requests" ("match_id" character(36) NOT NULL, "tx_id" character(36) NOT NULL, "requested_user_id" character(36) NOT NULL, "proposer_id" character(36) NOT NULL, "proposer_role" character varying(50) NOT NULL, "approver_id" character(36), "approver_role" character varying(50), "status" "public"."deposit_match_requests_status_enum" NOT NULL DEFAULT 'PENDING', "idempotency_key" character varying(64) NOT NULL, "proposed_at" TIMESTAMP(3) NOT NULL DEFAULT ('now'::text)::timestamp(3) with time zone, "resolved_at" TIMESTAMP(3), "audit_log" json NOT NULL DEFAULT (JSON_ARRAY()), CONSTRAINT "UQ_a9fbdee7007ec8d184f37b9da83" UNIQUE ("idempotency_key"), CONSTRAINT "PK_300b18945914e1eed9c873ecd2f" PRIMARY KEY ("match_id"))`);
        await queryRunner.query(`CREATE INDEX "idx_deposit_match_approver_date" ON "deposit_match_requests" ("approver_id", "resolved_at") `);
        await queryRunner.query(`CREATE INDEX "idx_deposit_match_proposer_date" ON "deposit_match_requests" ("proposer_id", "proposed_at") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "uk_deposit_match_tx" ON "deposit_match_requests" ("tx_id") `);
        await queryRunner.query(`ALTER TABLE "currency_networks" ADD CONSTRAINT "FK_5aaf9dee3ec9e7b7f7324c78f01" FOREIGN KEY ("currencyCurrencyId") REFERENCES "currencies"("currency_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "currency_networks" ADD CONSTRAINT "FK_82da04dcc43079dcf05ea1eb401" FOREIGN KEY ("currency_id") REFERENCES "currencies"("currency_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "market_pairs" ADD CONSTRAINT "FK_53f945c698b9bfb03485fceddf4" FOREIGN KEY ("base_currency_id") REFERENCES "currencies"("currency_id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "market_pairs" ADD CONSTRAINT "FK_8cfe588824a2ece145b8605afff" FOREIGN KEY ("quote_currency_id") REFERENCES "currencies"("currency_id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "managed_wallets" ADD CONSTRAINT "FK_1466375a8d7b7ee3d218dabdb59" FOREIGN KEY ("user_id") REFERENCES "users"("user_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "treasury_operations" ADD CONSTRAINT "FK_3f6c0cc779b6d7395f8eb5d57d1" FOREIGN KEY ("actor_user_id") REFERENCES "users"("user_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "treasury_operations" ADD CONSTRAINT "FK_843c87597640b2b0adbf2faa4a2" FOREIGN KEY ("from_wallet_id") REFERENCES "transaction_wallets"("wallet_id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "treasury_operations" ADD CONSTRAINT "FK_d95d258798d9b666f6ea823391d" FOREIGN KEY ("to_wallet_id") REFERENCES "transaction_wallets"("wallet_id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "withdrawals" ADD CONSTRAINT "FK_08bb514f5bafffed548bf47d15b" FOREIGN KEY ("userUserId") REFERENCES "users"("user_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "withdrawals" ADD CONSTRAINT "FK_4169fa1db359730be9569da57ce" FOREIGN KEY ("currencyCurrencyId") REFERENCES "currencies"("currency_id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "withdrawals" ADD CONSTRAINT "FK_3717c32c3be8fefceafc573185d" FOREIGN KEY ("networkNetworkId") REFERENCES "currency_networks"("network_id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "withdrawals" ADD CONSTRAINT "FK_0bd35ddb3acfb323ae3e024d2f8" FOREIGN KEY ("user_id") REFERENCES "users"("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "withdrawals" ADD CONSTRAINT "FK_0518d2ac219c3e9a166a56191a5" FOREIGN KEY ("currency_id") REFERENCES "currencies"("currency_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "withdrawals" ADD CONSTRAINT "FK_d399752fb458571ef212a88d959" FOREIGN KEY ("network_id") REFERENCES "currency_networks"("network_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wallets" ADD CONSTRAINT "FK_bbb8e4640ffea3ac7108e784f92" FOREIGN KEY ("userUserId") REFERENCES "users"("user_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wallets" ADD CONSTRAINT "FK_837954889dbeb41a6c30cdbe7e9" FOREIGN KEY ("currencyCurrencyId") REFERENCES "currencies"("currency_id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wallets" ADD CONSTRAINT "FK_92558c08091598f7a4439586cda" FOREIGN KEY ("user_id") REFERENCES "users"("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wallets" ADD CONSTRAINT "FK_b3167c57663ae949d67436465b3" FOREIGN KEY ("currency_id") REFERENCES "currencies"("currency_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wallet_ledger" ADD CONSTRAINT "FK_0e0e6726e03a81956190815d940" FOREIGN KEY ("userUserId") REFERENCES "users"("user_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wallet_ledger" ADD CONSTRAINT "FK_a7a7810f50ca5893139a38ca285" FOREIGN KEY ("currencyCurrencyId") REFERENCES "currencies"("currency_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wallet_ledger" ADD CONSTRAINT "FK_f3469cc7eb4db8a94b1a8c7c646" FOREIGN KEY ("walletWalletId") REFERENCES "wallets"("wallet_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wallet_ledger" ADD CONSTRAINT "FK_c7e9efe5a3b0a356eefbf012f64" FOREIGN KEY ("user_id") REFERENCES "users"("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wallet_ledger" ADD CONSTRAINT "FK_5b036a738ec1a48769929e3f4fd" FOREIGN KEY ("currency_id") REFERENCES "currencies"("currency_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wallet_ledger" ADD CONSTRAINT "FK_53d9fecd40f5fe635d119b49c4d" FOREIGN KEY ("wallet_id") REFERENCES "wallets"("wallet_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_76637a78ac19c65ad7d68bc4629" FOREIGN KEY ("creatorUserId") REFERENCES "users"("user_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_notifications" ADD CONSTRAINT "FK_cc0cb90a03b3eae2b0b838fa435" FOREIGN KEY ("userUserId") REFERENCES "users"("user_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_notifications" ADD CONSTRAINT "FK_be79f7f9718e0173f36c7079d2f" FOREIGN KEY ("notificationNotificationId") REFERENCES "notifications"("notification_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_a922b820eeef29ac1c6800e826a" FOREIGN KEY ("user_id") REFERENCES "users"("user_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_da7cd995471468f69515ee94602" FOREIGN KEY ("pair_id") REFERENCES "market_pairs"("pair_id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "trades" ADD CONSTRAINT "FK_2ac38269134019eedd1a1d93496" FOREIGN KEY ("pairPairId") REFERENCES "market_pairs"("pair_id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "trades" ADD CONSTRAINT "FK_32c5261279d8313220178cb5d6d" FOREIGN KEY ("takerOrderOrderId") REFERENCES "orders"("order_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "trades" ADD CONSTRAINT "FK_f8edaf9f143f926e23a3aa291e2" FOREIGN KEY ("makerOrderOrderId") REFERENCES "orders"("order_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "trades" ADD CONSTRAINT "FK_1347a4d264ca862d0a83f135ac3" FOREIGN KEY ("feeCurrencyCurrencyId") REFERENCES "currencies"("currency_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "trades" ADD CONSTRAINT "FK_8b861df9cd07c1dc0a9327248b2" FOREIGN KEY ("pair_id") REFERENCES "market_pairs"("pair_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "trades" ADD CONSTRAINT "FK_2a60ab74154d9cf3c9b6d707f78" FOREIGN KEY ("taker_order_id") REFERENCES "orders"("order_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "trades" ADD CONSTRAINT "FK_90aa85c756d868da86928de5440" FOREIGN KEY ("maker_order_id") REFERENCES "orders"("order_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "trades" ADD CONSTRAINT "FK_74e263555895d2f609823fe05d5" FOREIGN KEY ("fee_currency_id") REFERENCES "currencies"("currency_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "market_maker_configs" ADD CONSTRAINT "FK_27c2c71a1c90b5f05c0fb316839" FOREIGN KEY ("user_id") REFERENCES "users"("user_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "market_maker_configs" ADD CONSTRAINT "FK_7543fb447b1977d37f0914ff337" FOREIGN KEY ("pair_id") REFERENCES "market_pairs"("pair_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "fiat_deposits" ADD CONSTRAINT "FK_1587b331db09786db83184e4da7" FOREIGN KEY ("user_id") REFERENCES "users"("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "deposits" ADD CONSTRAINT "FK_72a0566d863a05155a3d4ffc7b2" FOREIGN KEY ("userUserId") REFERENCES "users"("user_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "deposits" ADD CONSTRAINT "FK_94c0c57b14c8ed166c47254c552" FOREIGN KEY ("currencyCurrencyId") REFERENCES "currencies"("currency_id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "deposits" ADD CONSTRAINT "FK_1d56aaa741ecfbed08ac42842da" FOREIGN KEY ("networkNetworkId") REFERENCES "currency_networks"("network_id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "deposits" ADD CONSTRAINT "FK_109b9d3209e5c344dae2ca8f221" FOREIGN KEY ("user_id") REFERENCES "users"("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "deposits" ADD CONSTRAINT "FK_dce38db03870f7a73551680ad68" FOREIGN KEY ("currency_id") REFERENCES "currencies"("currency_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "deposits" ADD CONSTRAINT "FK_50143130bceddb0866ed5ea5bf7" FOREIGN KEY ("network_id") REFERENCES "currency_networks"("network_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "admin_wallet_adjustments" ADD CONSTRAINT "FK_26cf876943e4c6af726046db3e5" FOREIGN KEY ("actorUserId") REFERENCES "users"("user_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "admin_wallet_adjustments" ADD CONSTRAINT "FK_71c7bd0d1c240754dec2918d1fc" FOREIGN KEY ("targetUserId") REFERENCES "users"("user_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "admin_wallet_adjustments" ADD CONSTRAINT "FK_3fd7cf8013b06e7f9720e023cc4" FOREIGN KEY ("currencyCurrencyId") REFERENCES "currencies"("currency_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "admin_wallet_adjustments" ADD CONSTRAINT "FK_08b21955e7696d392f255fc1063" FOREIGN KEY ("actor_user_id") REFERENCES "users"("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "admin_wallet_adjustments" ADD CONSTRAINT "FK_3ac62b375966aab85a60d2a9cc7" FOREIGN KEY ("target_user_id") REFERENCES "users"("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "admin_wallet_adjustments" ADD CONSTRAINT "FK_e20313b4868746354321c186b75" FOREIGN KEY ("currency_id") REFERENCES "currencies"("currency_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "linked_wallets" ADD CONSTRAINT "FK_f16fece22e5d7f356da24b2d4ca" FOREIGN KEY ("user_id") REFERENCES "users"("user_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "onchain_transactions" ADD CONSTRAINT "FK_49dca4628dec35a90e1cdfc8faf" FOREIGN KEY ("user_id") REFERENCES "users"("user_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "onchain_transactions" ADD CONSTRAINT "FK_0a95cfe31fe163189801cf58236" FOREIGN KEY ("linked_wallet_id") REFERENCES "linked_wallets"("link_id") ON DELETE SET NULL ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "onchain_transactions" DROP CONSTRAINT "FK_0a95cfe31fe163189801cf58236"`);
        await queryRunner.query(`ALTER TABLE "onchain_transactions" DROP CONSTRAINT "FK_49dca4628dec35a90e1cdfc8faf"`);
        await queryRunner.query(`ALTER TABLE "linked_wallets" DROP CONSTRAINT "FK_f16fece22e5d7f356da24b2d4ca"`);
        await queryRunner.query(`ALTER TABLE "admin_wallet_adjustments" DROP CONSTRAINT "FK_e20313b4868746354321c186b75"`);
        await queryRunner.query(`ALTER TABLE "admin_wallet_adjustments" DROP CONSTRAINT "FK_3ac62b375966aab85a60d2a9cc7"`);
        await queryRunner.query(`ALTER TABLE "admin_wallet_adjustments" DROP CONSTRAINT "FK_08b21955e7696d392f255fc1063"`);
        await queryRunner.query(`ALTER TABLE "admin_wallet_adjustments" DROP CONSTRAINT "FK_3fd7cf8013b06e7f9720e023cc4"`);
        await queryRunner.query(`ALTER TABLE "admin_wallet_adjustments" DROP CONSTRAINT "FK_71c7bd0d1c240754dec2918d1fc"`);
        await queryRunner.query(`ALTER TABLE "admin_wallet_adjustments" DROP CONSTRAINT "FK_26cf876943e4c6af726046db3e5"`);
        await queryRunner.query(`ALTER TABLE "deposits" DROP CONSTRAINT "FK_50143130bceddb0866ed5ea5bf7"`);
        await queryRunner.query(`ALTER TABLE "deposits" DROP CONSTRAINT "FK_dce38db03870f7a73551680ad68"`);
        await queryRunner.query(`ALTER TABLE "deposits" DROP CONSTRAINT "FK_109b9d3209e5c344dae2ca8f221"`);
        await queryRunner.query(`ALTER TABLE "deposits" DROP CONSTRAINT "FK_1d56aaa741ecfbed08ac42842da"`);
        await queryRunner.query(`ALTER TABLE "deposits" DROP CONSTRAINT "FK_94c0c57b14c8ed166c47254c552"`);
        await queryRunner.query(`ALTER TABLE "deposits" DROP CONSTRAINT "FK_72a0566d863a05155a3d4ffc7b2"`);
        await queryRunner.query(`ALTER TABLE "fiat_deposits" DROP CONSTRAINT "FK_1587b331db09786db83184e4da7"`);
        await queryRunner.query(`ALTER TABLE "market_maker_configs" DROP CONSTRAINT "FK_7543fb447b1977d37f0914ff337"`);
        await queryRunner.query(`ALTER TABLE "market_maker_configs" DROP CONSTRAINT "FK_27c2c71a1c90b5f05c0fb316839"`);
        await queryRunner.query(`ALTER TABLE "trades" DROP CONSTRAINT "FK_1347a4d264ca862d0a83f135ac3"`);
        await queryRunner.query(`ALTER TABLE "trades" DROP CONSTRAINT "FK_74e263555895d2f609823fe05d5"`);
        await queryRunner.query(`ALTER TABLE "trades" DROP CONSTRAINT "FK_90aa85c756d868da86928de5440"`);
        await queryRunner.query(`ALTER TABLE "trades" DROP CONSTRAINT "FK_2a60ab74154d9cf3c9b6d707f78"`);
        await queryRunner.query(`ALTER TABLE "trades" DROP CONSTRAINT "FK_8b861df9cd07c1dc0a9327248b2"`);
        await queryRunner.query(`ALTER TABLE "trades" DROP CONSTRAINT "FK_f8edaf9f143f926e23a3aa291e2"`);
        await queryRunner.query(`ALTER TABLE "trades" DROP CONSTRAINT "FK_32c5261279d8313220178cb5d6d"`);
        await queryRunner.query(`ALTER TABLE "trades" DROP CONSTRAINT "FK_2ac38269134019eedd1a1d93496"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_da7cd995471468f69515ee94602"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_a922b820eeef29ac1c6800e826a"`);
        await queryRunner.query(`ALTER TABLE "user_notifications" DROP CONSTRAINT "FK_be79f7f9718e0173f36c7079d2f"`);
        await queryRunner.query(`ALTER TABLE "user_notifications" DROP CONSTRAINT "FK_cc0cb90a03b3eae2b0b838fa435"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_76637a78ac19c65ad7d68bc4629"`);
        await queryRunner.query(`ALTER TABLE "wallet_ledger" DROP CONSTRAINT "FK_f3469cc7eb4db8a94b1a8c7c646"`);
        await queryRunner.query(`ALTER TABLE "wallet_ledger" DROP CONSTRAINT "FK_a7a7810f50ca5893139a38ca285"`);
        await queryRunner.query(`ALTER TABLE "wallet_ledger" DROP CONSTRAINT "FK_53d9fecd40f5fe635d119b49c4d"`);
        await queryRunner.query(`ALTER TABLE "wallet_ledger" DROP CONSTRAINT "FK_5b036a738ec1a48769929e3f4fd"`);
        await queryRunner.query(`ALTER TABLE "wallet_ledger" DROP CONSTRAINT "FK_c7e9efe5a3b0a356eefbf012f64"`);
        await queryRunner.query(`ALTER TABLE "wallet_ledger" DROP CONSTRAINT "FK_0e0e6726e03a81956190815d940"`);
        await queryRunner.query(`ALTER TABLE "wallets" DROP CONSTRAINT "FK_b3167c57663ae949d67436465b3"`);
        await queryRunner.query(`ALTER TABLE "wallets" DROP CONSTRAINT "FK_92558c08091598f7a4439586cda"`);
        await queryRunner.query(`ALTER TABLE "wallets" DROP CONSTRAINT "FK_837954889dbeb41a6c30cdbe7e9"`);
        await queryRunner.query(`ALTER TABLE "wallets" DROP CONSTRAINT "FK_bbb8e4640ffea3ac7108e784f92"`);
        await queryRunner.query(`ALTER TABLE "withdrawals" DROP CONSTRAINT "FK_d399752fb458571ef212a88d959"`);
        await queryRunner.query(`ALTER TABLE "withdrawals" DROP CONSTRAINT "FK_0518d2ac219c3e9a166a56191a5"`);
        await queryRunner.query(`ALTER TABLE "withdrawals" DROP CONSTRAINT "FK_0bd35ddb3acfb323ae3e024d2f8"`);
        await queryRunner.query(`ALTER TABLE "withdrawals" DROP CONSTRAINT "FK_3717c32c3be8fefceafc573185d"`);
        await queryRunner.query(`ALTER TABLE "withdrawals" DROP CONSTRAINT "FK_4169fa1db359730be9569da57ce"`);
        await queryRunner.query(`ALTER TABLE "withdrawals" DROP CONSTRAINT "FK_08bb514f5bafffed548bf47d15b"`);
        await queryRunner.query(`ALTER TABLE "treasury_operations" DROP CONSTRAINT "FK_3f6c0cc779b6d7395f8eb5d57d1"`);
        await queryRunner.query(`ALTER TABLE "treasury_operations" DROP CONSTRAINT "FK_d95d258798d9b666f6ea823391d"`);
        await queryRunner.query(`ALTER TABLE "treasury_operations" DROP CONSTRAINT "FK_843c87597640b2b0adbf2faa4a2"`);
        await queryRunner.query(`ALTER TABLE "managed_wallets" DROP CONSTRAINT "FK_1466375a8d7b7ee3d218dabdb59"`);
        await queryRunner.query(`ALTER TABLE "market_pairs" DROP CONSTRAINT "FK_8cfe588824a2ece145b8605afff"`);
        await queryRunner.query(`ALTER TABLE "market_pairs" DROP CONSTRAINT "FK_53f945c698b9bfb03485fceddf4"`);
        await queryRunner.query(`ALTER TABLE "currency_networks" DROP CONSTRAINT "FK_82da04dcc43079dcf05ea1eb401"`);
        await queryRunner.query(`ALTER TABLE "currency_networks" DROP CONSTRAINT "FK_5aaf9dee3ec9e7b7f7324c78f01"`);
        await queryRunner.query(`DROP INDEX "public"."uk_deposit_match_tx"`);
        await queryRunner.query(`DROP INDEX "public"."idx_deposit_match_proposer_date"`);
        await queryRunner.query(`DROP INDEX "public"."idx_deposit_match_approver_date"`);
        await queryRunner.query(`DROP TABLE "deposit_match_requests"`);
        await queryRunner.query(`DROP TYPE "public"."deposit_match_requests_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."uk_onchain_tx_chain_hash_log"`);
        await queryRunner.query(`DROP INDEX "public"."idx_onchain_tx_user"`);
        await queryRunner.query(`DROP INDEX "public"."idx_onchain_tx_created"`);
        await queryRunner.query(`DROP INDEX "public"."idx_onchain_tx_treasury_operation"`);
        await queryRunner.query(`DROP TABLE "onchain_transactions"`);
        await queryRunner.query(`DROP TYPE "public"."onchain_transactions_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."onchain_transactions_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."onchain_transactions_chain_enum"`);
        await queryRunner.query(`DROP INDEX "public"."uk_linked_wallet_user_chain_addr"`);
        await queryRunner.query(`DROP INDEX "public"."idx_linked_wallet_user"`);
        await queryRunner.query(`DROP TABLE "linked_wallets"`);
        await queryRunner.query(`DROP TYPE "public"."linked_wallets_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."linked_wallets_chain_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_adj_actor"`);
        await queryRunner.query(`DROP INDEX "public"."idx_adj_target"`);
        await queryRunner.query(`DROP INDEX "public"."idx_adj_created"`);
        await queryRunner.query(`DROP TABLE "admin_wallet_adjustments"`);
        await queryRunner.query(`DROP TYPE "public"."admin_wallet_adjustments_type_enum"`);
        await queryRunner.query(`DROP TABLE "app_settings"`);
        await queryRunner.query(`DROP TABLE "deposit_watcher_cursors"`);
        await queryRunner.query(`DROP INDEX "public"."uk_deposit_tx"`);
        await queryRunner.query(`DROP INDEX "public"."idx_deposit_user"`);
        await queryRunner.query(`DROP TABLE "deposits"`);
        await queryRunner.query(`DROP TYPE "public"."deposits_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_exchange_rate_audit_changed_by"`);
        await queryRunner.query(`DROP INDEX "public"."idx_exchange_rate_audit_created_at"`);
        await queryRunner.query(`DROP TABLE "exchange_rate_audit_log"`);
        await queryRunner.query(`DROP INDEX "public"."idx_fiat_deposits_user"`);
        await queryRunner.query(`DROP INDEX "public"."idx_fiat_deposits_order_code"`);
        await queryRunner.query(`DROP TABLE "fiat_deposits"`);
        await queryRunner.query(`DROP TYPE "public"."fiat_deposits_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_integration_outbox_unpublished"`);
        await queryRunner.query(`DROP INDEX "public"."idx_integration_outbox_topic_unpublished"`);
        await queryRunner.query(`DROP INDEX "public"."idx_integration_outbox_retry"`);
        await queryRunner.query(`DROP TABLE "integration_outbox"`);
        await queryRunner.query(`DROP INDEX "public"."uk_mm_cfg_user_pair"`);
        await queryRunner.query(`DROP INDEX "public"."idx_mm_cfg_active"`);
        await queryRunner.query(`DROP TABLE "market_maker_configs"`);
        await queryRunner.query(`DROP INDEX "public"."idx_pmc_type_network_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_pmc_status"`);
        await queryRunner.query(`DROP TABLE "payment_method_configs"`);
        await queryRunner.query(`DROP TYPE "public"."payment_method_configs_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."payment_method_configs_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_processed_integration_events_consumer_event"`);
        await queryRunner.query(`DROP TABLE "processed_integration_events"`);
        await queryRunner.query(`DROP INDEX "public"."idx_read_market_ohlcv_pair_interval_time"`);
        await queryRunner.query(`DROP TABLE "read_market_ohlcv"`);
        await queryRunner.query(`DROP INDEX "public"."idx_read_market_pairs_symbol"`);
        await queryRunner.query(`DROP TABLE "read_market_pairs"`);
        await queryRunner.query(`DROP INDEX "public"."idx_read_market_tickers_symbol"`);
        await queryRunner.query(`DROP TABLE "read_market_tickers"`);
        await queryRunner.query(`DROP INDEX "public"."idx_read_market_trades_pair_executed"`);
        await queryRunner.query(`DROP TABLE "read_market_trades"`);
        await queryRunner.query(`DROP INDEX "public"."idx_read_onchain_deposits_user_created"`);
        await queryRunner.query(`DROP TABLE "read_onchain_deposits"`);
        await queryRunner.query(`DROP TABLE "system_configs"`);
        await queryRunner.query(`DROP TYPE "public"."system_configs_category_enum"`);
        await queryRunner.query(`DROP TYPE "public"."system_configs_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_audit_pair_time"`);
        await queryRunner.query(`DROP INDEX "public"."idx_audit_trade"`);
        await queryRunner.query(`DROP TABLE "trade_audit_log"`);
        await queryRunner.query(`DROP INDEX "public"."idx_trades_pair_time"`);
        await queryRunner.query(`DROP INDEX "public"."idx_trades_taker"`);
        await queryRunner.query(`DROP INDEX "public"."idx_trades_maker"`);
        await queryRunner.query(`DROP TABLE "trades"`);
        await queryRunner.query(`DROP INDEX "public"."uk_order_idem"`);
        await queryRunner.query(`DROP INDEX "public"."idx_orders_user"`);
        await queryRunner.query(`DROP INDEX "public"."idx_orders_pair_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_orders_book"`);
        await queryRunner.query(`DROP TABLE "orders"`);
        await queryRunner.query(`DROP TYPE "public"."orders_time_in_force_enum"`);
        await queryRunner.query(`DROP TYPE "public"."orders_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."orders_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."orders_side_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_tmw_chain"`);
        await queryRunner.query(`DROP INDEX "public"."idx_tmw_chain_default"`);
        await queryRunner.query(`DROP INDEX "public"."idx_tmw_status"`);
        await queryRunner.query(`DROP INDEX "public"."uk_tmw_chain_address"`);
        await queryRunner.query(`DROP TABLE "treasury_main_wallets"`);
        await queryRunner.query(`DROP TYPE "public"."treasury_main_wallets_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."treasury_main_wallets_chain_enum"`);
        await queryRunner.query(`DROP INDEX "public"."uk_user_notif"`);
        await queryRunner.query(`DROP INDEX "public"."idx_un_user_unread"`);
        await queryRunner.query(`DROP TABLE "user_notifications"`);
        await queryRunner.query(`DROP INDEX "public"."idx_notifications_created_at"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."uk_ledger_ref"`);
        await queryRunner.query(`DROP INDEX "public"."idx_ledger_user_time"`);
        await queryRunner.query(`DROP INDEX "public"."idx_ledger_ref"`);
        await queryRunner.query(`DROP TABLE "wallet_ledger"`);
        await queryRunner.query(`DROP TYPE "public"."wallet_ledger_direction_enum"`);
        await queryRunner.query(`DROP TYPE "public"."wallet_ledger_ref_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."uk_wallet_user_currency"`);
        await queryRunner.query(`DROP INDEX "public"."idx_wallet_user"`);
        await queryRunner.query(`DROP TABLE "wallets"`);
        await queryRunner.query(`DROP INDEX "public"."uk_withdraw_idem"`);
        await queryRunner.query(`DROP INDEX "public"."idx_withdraw_user"`);
        await queryRunner.query(`DROP TABLE "withdrawals"`);
        await queryRunner.query(`DROP TYPE "public"."withdrawals_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."uk_users_email"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
        await queryRunner.query(`DROP TYPE "public"."users_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_treasury_op_chain_type_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_treasury_op_created"`);
        await queryRunner.query(`DROP TABLE "treasury_operations"`);
        await queryRunner.query(`DROP TYPE "public"."treasury_operations_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."treasury_operations_chain_enum"`);
        await queryRunner.query(`DROP TYPE "public"."treasury_operations_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."uk_tx_wallet_chain_address"`);
        await queryRunner.query(`DROP INDEX "public"."idx_tx_wallet_chain_purpose"`);
        await queryRunner.query(`DROP INDEX "public"."idx_tx_wallet_chain_active"`);
        await queryRunner.query(`DROP TABLE "transaction_wallets"`);
        await queryRunner.query(`DROP TYPE "public"."transaction_wallets_purpose_enum"`);
        await queryRunner.query(`DROP TYPE "public"."transaction_wallets_chain_enum"`);
        await queryRunner.query(`DROP INDEX "public"."uk_managed_wallet_user_chain_addr"`);
        await queryRunner.query(`DROP INDEX "public"."idx_managed_wallet_chain_default"`);
        await queryRunner.query(`DROP INDEX "public"."idx_managed_wallet_user_active"`);
        await queryRunner.query(`DROP TABLE "managed_wallets"`);
        await queryRunner.query(`DROP TYPE "public"."managed_wallets_chain_enum"`);
        await queryRunner.query(`DROP INDEX "public"."uk_currency_symbol"`);
        await queryRunner.query(`DROP TABLE "currencies"`);
        await queryRunner.query(`DROP INDEX "public"."uk_pair_symbol"`);
        await queryRunner.query(`DROP INDEX "public"."uk_pair_base_quote"`);
        await queryRunner.query(`DROP INDEX "public"."idx_pair_active"`);
        await queryRunner.query(`DROP TABLE "market_pairs"`);
        await queryRunner.query(`DROP INDEX "public"."uk_currency_network"`);
        await queryRunner.query(`DROP TABLE "currency_networks"`);
    }

}
